### ISSUE TITLE
Tabs (JavaScript) are not working

### ISSUE THREAD

**Issue by roryheaney** [coliff/bootstrap-ie11#39]
I noticed there wasn't a Tabs example?

Is that because there isn't a polyfill for the SelectorEngine function?

**Comment by coliff** [comment]
Thanks for spotting this! I added an example - and you're right - it isn't working on IE 11.
https://coliff.github.io/bootstrap-ie11/tests/#tabs

I've added the 'Help wanted' label to this issue. If anyone knows how to fix (ideally with polyfill.io) please let me know.

**Comment by roryheaney** [comment]
I'm currently using BS 5 and Tabs was the only issue I had with IE 11.  

I'm currently including the Tab plugin itself in IE only ( along with it's Utility reference ). 

I also run an if statement, if IE, instead of `data-bs-toggle="tab"`, use `data-toggle="tab"`.

It's not he cleanest option, but allows you to use BS 5 and still support IE 11.

**Comment by battlehater** [comment]
Hey. I don't speak english, but i'll try :)
IE throws with error, because does not support :scope selector.
Solution is simple: just include polyfill: https://cdn.jsdelivr.net/npm/element-qsa-scope@1.1.0/index.min.js (or https://www.npmjs.com/package/element-qsa-scope).
Translate it into human english please :)

**Comment by coliff** [comment]
Thanks for the info @battlehater ! I've added a link to that polyfill from the demo page at: https://coliff.github.io/bootstrap-ie11/tests/#tabs

It can be loaded like this: `<script nomodule src="https://cdn.jsdelivr.net/npm/element-qsa-scope@1.1.0/index.min.js"></script>` so that it doesn't load on modern browsers (which don't need the polyfill).
